### ISSUE TITLE
Record

### ISSUE THREAD

**Issue by nickkostov** [NeonSludge/ansible-dns-inventory#11]
I did not understand how do you set up the txt record ?

**Comment by NeonSludge** [comment]
That depends on the DNS server and the inventory mode you're using.

Let's say you're using the default mode of operation (the one that uses a DNS zone transfer to acquire the records) and you want to add a record for the host from the first example in the README file.

For bind9 you would edit the DNS zone file for the `infra.local` zone and add something like:
```
app01      IN           TXT         "OS=linux;ENV=dev;ROLE=app;SRV=tomcat_backend_auth"
```

For dnsmasq this would require a line in the configuration file:
```
txt-record=app01.infra.local,"OS=linux;ENV=dev;ROLE=app;SRV=tomcat_backend_auth"
```

In the future I plan to add support for something like a key-value store (etcd, Consul) or a local SQLite database to hold these records, so that you're not required to have a DNS server to use this tool.

Now, if your question is about the format of the TXT records themselves then there is no real "right" way to set them up.
You have [five available attributes](https://github.com/NeonSludge/ansible-dns-inventory#host-attributes-default-key-names) that any host can have. You then add a TXT record to your DNS server for every host that should be managed by Ansible, setting these attributes according to what role these hosts play in your infrastructure.
For example, if you have a Linux host with a Nginx reverse proxy that is related to your production environment then its TXT record might look like this:
```
OS=linux;ENV=prod;ROLE=proxy;SRV=nginx
```
Now you have a group that you can use to address all proxies (`prod_proxy`) and all Nginx proxies (`prod_proxy_nginx`) in your production environment 
You can take this further and make the service identifier (the `SRV` attribute) more specific. Let's say your Nginx proxy deals with requests to some file storage service. You can transform its TXT record into something like this:
```
OS=linux;ENV=prod;ROLE=proxy;SRV=nginx_filestorage
```
You now have an additional group that this host belongs to: `prod_proxy_nginx_filestorage`. So now you can also address all Nginx proxies in your production environment that relay requests to your file storage service.
What's also important is the fact that all these groups belong to one branch of one big group tree so the `prod_proxy_nginx` group inherits variables from the `prod_proxy` group, the `prod_proxy_nginx_filestorage` group inherits from the `prod_proxy_nginx` group and so on.
You can have any number of these branches of any length and all this is done automatically, you just have to set the host attributes.

**Comment by nickkostov** [comment]
Thanks, mate
